name: Build MSI Installer with JavaFX Runtime

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Build project
        run: mvn clean package

      - name: Copy runtime dependencies
        shell: pwsh
        run: |
          mvn -B dependency:copy-dependencies -DincludeScope=runtime -Dmdep.useBaseVersion=true

          Copy-Item target/dependency/*.jar target/

      - name: Download and extract JavaFX JMODs
        run: |
          curl -L -o javafx-jmods.zip https://download2.gluonhq.com/openjfx/20.0.2/openjfx-20.0.2_windows-x64_bin-jmods.zip
          powershell -command "Expand-Archive -Path 'javafx-jmods.zip' -DestinationPath 'javafx-jmods-temp'"
          move javafx-jmods-temp\\javafx-jmods-20.0.2 javafx-jmods

      - name: List .jmod files
        run: dir javafx-jmods
        shell: cmd

      - name: Create runtime with jlink
        run: |
          jlink ^
            --module-path "%JAVA_HOME%\jmods;javafx-jmods" ^
            --add-modules java.base,java.desktop,java.sql,javafx.controls,javafx.fxml ^
            --output custom-runtime ^
            --strip-debug ^
            --compress 2 ^
            --no-header-files ^
            --no-man-pages
        shell: cmd

      - name: Verificar contenido del JAR
        run: jar tf target/aluFx-1.0-SNAPSHOT.jar
        shell: cmd

      - name: Descargar y extraer MariaDB
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://archive.mariadb.org/mariadb-10.11.6/winx64-packages/mariadb-10.11.6-winx64.zip -OutFile mariadb.zip
          Expand-Archive mariadb.zip -DestinationPath mariadb-temp
          Move-Item -Path 'mariadb-temp\mariadb-10.11.6-winx64\*' -Destination 'mariadb' -Force
          Remove-Item -Recurse -Force mariadb-temp, mariadb.zip

      - name: Package MSI with jpackage
        run: |
          jpackage ^
            --type msi ^
            --name aluFx ^
            --input target ^
            --main-jar aluFx-1.0-SNAPSHOT.jar ^
            --main-class com.meztli.alufx.HelloApplication ^
            --runtime-image custom-runtime ^
            --app-version 1.1 ^
            --win-menu ^
            --win-console ^
            --win-shortcut ^
            --java-options -Dfile.encoding=UTF-8 ^
            --resource-dir . ^
            --dest target/installer
        shell: cmd

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: aluFx-installer
          path: target/installer/aluFx-1.1.msi
