name: Build Installer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Build with Maven
        run: mvn clean package

      - name: Detect platform-specific jpackage type
        id: package-type
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "type=msi" >> $GITHUB_OUTPUT
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            echo "type=pkg" >> $GITHUB_OUTPUT
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            echo "type=deb" >> $GITHUB_OUTPUT
          fi

      - name: Package installer
        run: |
          jpackage \
            --type ${{ steps.package-type.outputs.type }} \
            --name aluFx \
            --input target \
            --main-jar aluFx-1.0-SNAPSHOT.jar \
            --main-class com.meztli.alufx.HelloApplication \
            --app-version 1.0 \
            --java-options -Dfile.encoding=UTF-8 \
            --dest target/installer
        shell: bash