name: Build MSI Installer with JavaFX Runtime

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Build project with Maven
        run: mvn clean package

      - name: verify fxml
        run: jar tf target/aluFx-1.0-SNAPSHOT.jar | findstr main-view.fxml

      - name: Download JavaFX JMODs
        run: |
          curl -L -o javafx-jmods.zip https://download2.gluonhq.com/openjfx/20.0.2/openjfx-20.0.2_windows-x64_bin-jmods.zip
          powershell -command "Expand-Archive -Path 'javafx-jmods.zip' -DestinationPath 'javafx-jmods'"

      - name: Create custom runtime with jlink
        run: |
          jlink ^
            --module-path "%JAVA_HOME%\jmods;javafx-jmods\javafx-jmods\jmods" ^
            --add-modules java.base,java.desktop,java.sql,javafx.controls,javafx.fxml ^
            --output custom-runtime ^
            --strip-debug ^
            --compress 2 ^
            --no-header-files ^
            --no-man-pages
        shell: cmd

      - name: Package MSI installer with jpackage
        run: |
          jpackage ^
            --type msi ^
            --name aluFx ^
            --input target ^
            --main-jar aluFx-1.0-SNAPSHOT.jar ^
            --main-class com.meztli.alufx.HelloApplication ^
            --runtime-image custom-runtime ^
            --app-version 1.0 ^
            --win-menu ^
            --win-shortcut ^
            --java-options -Dfile.encoding=UTF-8 ^
            --dest target/installer
        shell: cmd

      - name: Upload MSI installer
        uses: actions/upload-artifact@v4
        with:
          name: aluFx-installer
          path: target/installer/aluFx-1.0.msi
